name: Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setting up Golang
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25.0
          elixir-version: 1.14.4
      - name: Run tests
        run: mix test
